#ciclo iterativo while controlado por condiciones

"""manzanas = 1000
contador = 0
print(f"se ha iniciado el carrito. En total hay {contador} manzanas")

while(contador < manzanas):
    contador=contador+1
    print(f"Se ha agregado una manzana a la canasta. Ahora hay {contador} manzanas.")
"""

#ciclo iterativo while controlado por cantidades

print(f"se ha iniciado el carrito. En total hay 0 manzanas.")
for i in range (1,8):
    print(f"se ha agregado una manzana a la canasta. Ahora hay {i} manzanas.")
